[accelerator]
accelerator_manufacturer = "NVIDIA"
accelerator_memory_type = "DDR3"
accelerator_count = 1
accelerator_api = "CUDA_5_0;OpenCL_3_0;unset;unset;OpenGL_4_6;Vulkan_1_3;DirectX_11_0"
accelerator_architecture = "Maxwell"
accelerator = "NVIDIAGeForce_940MX"
accelerator_processor_count = "1"
accelerator_processor = "GM108M"
accelerator_memory_size = "4G"
accelerator_tdp = "23"
accelerator_type = "GPU"

[processor]
processor_core_count = 2
processor_count = 1
processor_core_threads_count = 2
processor_simd = "AVX2"
processor_core_L2_size = 262144
processor_L3_size = 4194304
processor_core_L1_size = 32768
processor_core_clock = 2900
processor_manufacturer = "Intel"
processor_isa = "ISA_x86_64_v3"
processor_tdp = 15
processor = "IntelCore_i7_7500U"
processor_microarchitecture = "KabyLake"

[interconnection]
interconnection_latency = "unset"
interconnection = "unset"
interconnection_bandwidth = "unset"
interconnection_startuptime = "unset"
interconnection_RDMA = "unset"
interconnection_topology = "unset"

[storage]
storage_bandwidth = "unset"
storage_type = "SSD"
storage_latency = "unset"
storage_size = 960197124096
storage_networkbandwidth = "unset"
storage_interface = "SATA"

[memory]
node_memory_frequency = 2400
node_memory_size = 17179869184
node_memory_latency = "unset"
node_memory_type = "DDR4"
node_memory_bandwidth = 2133

[node]
node_dedicated = "No"
node_virtual = "No"
node_machinetype = "unset"
node_machinefamily = "unset"
node_provider = "OnPremise"
node_vcpus_count = "unset"
