@platform parameter clear
@platform parameter processor_count
@platform parameter processor_core_count
@platform parameter accelerator_count
@platform parameter accelerator_manufacturer
@platform parameter accelerator_api
@platform parameter node_provider
@platform parameter node_vcpus_count
@platform parameter node_count
